language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

before_script:
    - composer self-update
    - composer update

script:
    - vendor/bin/phpunit --coverage-clover=./tests/coverage/clover.xml --coverage-html=./tests/coverage/html

after_success:
    - bash <(curl -s https://codecov.io/bash)